export class Save {
    constructor (public points: number,
                 public pointsPS:number,
                 public pointsPC:number,
                 public lowCount:number,
                 public medCount:number,
                 public strCount:number,
                 public twiceClick:number,
                 public superClick:number,
                 public turboClick:number,
                 public manyClick:number,
                 public coastClick:number,
                 public lastClickBuff:number,
                 public twPrice:number,
                 public spPrice:number,
                 public trbPrice:number,
                 public mnPrice:number,
                 public vcPrice:number,
                 public lstPrice:number,
                 public lowPrice:number,
                 public medPrice:number,
                 public strPrice:number,){}
}